# Generated by Django 4.2.8 on 2026-03-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='discount_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
